development:
  bucket: media-dev.icoddle.com
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']

test:
  bucket: media-dev.icoddle.com
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']

production:
  bucket: media.icoddle.com
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
